apiVersion: v1
data:
  service.slack: |
    token: 'https://hooks.slack.com/services/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'
  trigger.on-sync-status-healthy: "- description: Application sync state is healthy\n
    \ send: [slack]\n  message: |\n    :white_check_mark: *Application Sync Success*
    \ \n    Application *nodejs-app* has successfully synced.  \n    *Revision*: `85b528a1bf075c08a1398899ce163690991bc32c`
    \ \n    *Health Status*: Healthy  \n    *Sync Status*: Synced to HEAD  \n    *Duration*:
    0s  \n    All tasks have run successfully.\n"
  trigger.on-sync-status-unknown: |
    - description: Application sync state is unknown
      send: [slack]
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"service.slack":"token: https://hooks.slack.com/services/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\n","trigger.on-sync-status-healthy":"- description: Application sync state is healthy\n  send: [slack]\n  message: |\n    :white_check_mark: *Application Sync Success*  \n    Application *nodejs-app* has successfully synced.  \n    *Revision*: `85b528a1bf075c08a1398899ce163690991bc32c`  \n    *Health Status*: Healthy  \n    *Sync Status*: Synced to HEAD  \n    *Duration*: 0s  \n    All tasks have run successfully.\n","trigger.on-sync-status-unknown":"- description: Application sync state is unknown\n  send: [slack]\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2025-03-26T23:05:10Z","name":"argocd-notifications-cm","namespace":"argocd","resourceVersion":"124778","uid":"a6d04fb5-36d9-4833-99c8-b519f7546724"}}
  creationTimestamp: "2025-03-26T23:05:10Z"
  name: argocd-notifications-cm
  namespace: argocd
  resourceVersion: "129527"
  uid: a6d04fb5-36d9-4833-99c8-b519f7546724
