apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: 008971661977.dkr.ecr.us-east-1.amazonaws.com/nodejs-app
    argocd-image-updater.argoproj.io/nodejs-app.update-strategy: latest
spec:
  project: default
  source:
    repoURL: https://github.com/bezkoder/nodejs-express-mysql.git
    targetRevision: HEAD
    path: /
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
